"""MatAnyone 2 matting processor.

Uses a memory-based approach that requires a first-frame
segmentation mask. The mask is generated by SAM2 (see
sam2_masks.py) and fed into InferenceCore's memory before
frame processing begins.
"""

import numpy as np
import torch
from loguru import logger

from vrautomatte.utils.gpu import get_device

# Re-export mask functions for backward compatibility
from vrautomatte.pipeline.sam2_masks import (  # noqa: F401
    generate_first_frame_mask,
    generate_pov_body_mask,
    _mask_center_of_mass,
    _select_non_pov_mask,
    _select_pov_body_mask,
)


class MatAnyone2Processor:
    """Process video frames through MatAnyone 2.

    Requires a first-frame mask (from SAM2 or manual input).
    Uses InferenceCore.step() for per-frame matting with
    recurrent memory propagation.

    Args:
        first_frame_mask: Binary mask (H, W), uint8.
        device: Target device. Auto-detected if None.
    """

    def __init__(
        self,
        first_frame_mask: np.ndarray,
        device: torch.device | None = None,
    ):
        try:
            from matanyone2 import MatAnyone2, InferenceCore
        except ImportError:
            raise ImportError(
                "matanyone2 is required. "
                "Install with: uv sync --extra matanyone2"
            )

        if device is None:
            device = get_device()

        self.device = device
        self._mask = first_frame_mask
        self._is_first_frame = True

        logger.info(f"Loading MatAnyone 2 on {device}...")
        model = MatAnyone2.from_pretrained(
            "PeiqingYang/MatAnyone2"
        )
        self._processor = InferenceCore(
            model, device=str(device)
        )
        logger.info("MatAnyone 2 loaded")

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process a single frame and return the alpha matte.

        Args:
            frame: RGB array (H, W, 3), uint8.

        Returns:
            Alpha matte (H, W), uint8 (0-255).
        """
        img_tensor = (
            torch.from_numpy(frame).float().permute(2, 0, 1)
            / 255.0
        ).to(self.device)

        with torch.no_grad():
            if self._is_first_frame:
                # Step 1: feed mask into memory
                mask_tensor = torch.from_numpy(
                    self._mask
                ).float().to(self.device)
                self._processor.step(
                    img_tensor,
                    mask_tensor,
                    objects=[1],
                )
                # Step 2: predict using that memory
                output = self._processor.step(
                    img_tensor,
                    first_frame_pred=True,
                )
                self._is_first_frame = False
            else:
                output = self._processor.step(img_tensor)

        # Extract alpha from output probabilities
        matte = self._processor.output_prob_to_mask(output)
        matte = (matte * 255).byte().cpu().numpy()
        if matte.ndim == 3:
            matte = matte[0]
        return matte

    def reset(self) -> None:
        """Reset state for a new video."""
        self._is_first_frame = True

    def cleanup(self) -> None:
        """Release model and GPU memory."""
        if hasattr(self, "_processor"):
            del self._processor
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        logger.debug("MatAnyone 2 processor cleaned up")
