"""MatAnyone 2 matting processor.

Uses a memory-based approach that requires a first-frame
segmentation mask. The mask is generated by SAM2 (see
sam2_masks.py) and fed into InferenceCore's memory before
frame processing begins.

Scene changes are detected via histogram correlation. When
a drastic change occurs (e.g. laying → standing POV), SAM2
regenerates the mask and InferenceCore's memory is reset.
"""

import numpy as np
import torch
from loguru import logger

from vrautomatte.utils.gpu import get_device

# Re-export mask functions for backward compatibility
from vrautomatte.pipeline.sam2_masks import (  # noqa: F401
    generate_first_frame_mask,
    generate_pov_body_mask,
    _mask_center_of_mass,
    _select_non_pov_mask,
    _select_person_mask,
    _select_pov_body_mask,
)


class MatAnyone2Processor:
    """Process video frames through MatAnyone 2.

    Requires a first-frame mask (from SAM2 or manual input).
    Uses InferenceCore.step() for per-frame matting with
    recurrent memory propagation.

    In POV mode, monitors for scene changes and regenerates
    the mask via SAM2 when detected.

    Args:
        first_frame_mask: Binary mask (H, W), uint8.
        device: Target device. Auto-detected if None.
        pov_mode: Enable scene change detection for mask
            refresh. Default False.
    """

    def __init__(
        self,
        first_frame_mask: np.ndarray,
        device: torch.device | None = None,
        pov_mode: bool = False,
    ):
        try:
            from matanyone2 import MatAnyone2, InferenceCore
        except ImportError:
            raise ImportError(
                "matanyone2 is required. "
                "Install with: uv sync --extra matanyone2"
            )

        if device is None:
            device = get_device()

        self.device = device
        self._mask = first_frame_mask
        self._is_first_frame = True
        self._pov_mode = pov_mode
        self._scene_detector = None

        if pov_mode:
            from vrautomatte.pipeline.scene_detect import (
                SceneChangeDetector,
            )
            self._scene_detector = SceneChangeDetector()

        logger.info(f"Loading MatAnyone 2 on {device}...")
        model = MatAnyone2.from_pretrained(
            "PeiqingYang/MatAnyone2"
        )
        self._processor = InferenceCore(
            model, device=str(device)
        )
        logger.info("MatAnyone 2 loaded")

    def _reinit_with_mask(
        self, frame: np.ndarray, mask: np.ndarray
    ) -> np.ndarray:
        """Reinitialize memory with a new mask.

        Clears InferenceCore state and feeds the new mask,
        then predicts on the current frame.

        Returns:
            Alpha matte for the current frame.
        """
        self._mask = mask
        self._processor.clear_memory()
        self._processor.object_manager = type(
            self._processor.object_manager
        )()
        self._is_first_frame = True
        return self._process_first_frame(frame)

    def _process_first_frame(
        self, frame: np.ndarray
    ) -> np.ndarray:
        """Run the two-step first-frame initialization."""
        img_tensor = (
            torch.from_numpy(frame).float().permute(2, 0, 1)
            / 255.0
        ).to(self.device)

        with torch.no_grad():
            mask_tensor = torch.from_numpy(
                self._mask
            ).float().to(self.device)
            self._processor.step(
                img_tensor,
                mask_tensor,
                objects=[1],
            )
            output = self._processor.step(
                img_tensor,
                first_frame_pred=True,
            )

        self._is_first_frame = False
        return self._extract_matte(output)

    def _extract_matte(self, output) -> np.ndarray:
        """Convert model output to uint8 matte."""
        matte = self._processor.output_prob_to_mask(output)
        matte = (matte * 255).byte().cpu().numpy()
        if matte.ndim == 3:
            matte = matte[0]
        return matte

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process a single frame and return the alpha matte.

        Checks for scene changes in POV mode and regenerates
        the mask if needed.

        Args:
            frame: RGB array (H, W, 3), uint8.

        Returns:
            Alpha matte (H, W), uint8 (0-255).
        """
        # Scene change detection (POV mode only)
        if (
            self._scene_detector is not None
            and not self._is_first_frame
            and self._scene_detector.check(frame)
        ):
            from vrautomatte.pipeline.sam2_masks import (
                generate_first_frame_mask,
            )
            logger.info(
                "Scene change — regenerating MA2 mask"
            )
            new_mask = generate_first_frame_mask(
                frame, self.device, pov_mode=True
            )
            matte = self._reinit_with_mask(frame, new_mask)
            self._scene_detector.update_reference(frame)
            return matte

        if self._is_first_frame:
            matte = self._process_first_frame(frame)
            if self._scene_detector is not None:
                self._scene_detector.update_reference(frame)
            return matte

        img_tensor = (
            torch.from_numpy(frame).float().permute(2, 0, 1)
            / 255.0
        ).to(self.device)

        with torch.no_grad():
            output = self._processor.step(img_tensor)

        return self._extract_matte(output)

    def reset(self) -> None:
        """Reset state for a new video."""
        self._is_first_frame = True
        if self._scene_detector is not None:
            self._scene_detector.reset()

    def cleanup(self) -> None:
        """Release model and GPU memory."""
        if hasattr(self, "_processor"):
            del self._processor
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        logger.debug("MatAnyone 2 processor cleaned up")
