"""AI matte generation — protocol and factory.

Supports pluggable matting backends:
- RVM (Robust Video Matting): fully automatic, no first-frame mask
- MatAnyone 2: requires first-frame mask (auto-generated by SAM2)

All processors implement the MatteProcessor protocol so the pipeline
runner can use them interchangeably.
"""

from typing import Protocol, runtime_checkable

import numpy as np
import torch
from loguru import logger

from vrautomatte.utils.gpu import get_device

# Valid model variant names
VARIANTS = ["mobilenetv3", "resnet50", "matanyone2"]


@runtime_checkable
class MatteProcessor(Protocol):
    """Protocol for video matting processors."""

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process a single RGB frame → alpha matte.

        Args:
            frame: RGB array (H, W, 3), uint8.

        Returns:
            Alpha matte (H, W), uint8 (0-255).
        """
        ...

    def reset(self) -> None:
        """Reset internal state between videos."""
        ...

    def cleanup(self) -> None:
        """Release GPU memory and model resources."""
        ...


def create_processor(
    variant: str,
    device: torch.device | None = None,
    downsample_ratio: float = 0.25,
    first_frame: np.ndarray | None = None,
) -> MatteProcessor:
    """Create a matting processor for the given variant.

    For matanyone2: generates SAM2 mask from first_frame,
    unloads SAM2, then loads MatAnyone 2 (D003).

    Args:
        variant: One of 'mobilenetv3', 'resnet50', 'matanyone2'.
        device: Target device. Auto-detected if None.
        downsample_ratio: RVM downscale (ignored for MA2).
        first_frame: First video frame (required for matanyone2).

    Returns:
        A MatteProcessor instance.
    """
    if variant in ("mobilenetv3", "resnet50"):
        from vrautomatte.pipeline.rvm import RVMProcessor
        return RVMProcessor(
            variant=variant,
            downsample_ratio=downsample_ratio,
            device=device,
        )

    if variant == "matanyone2":
        from vrautomatte.pipeline.matanyone2 import (
            MatAnyone2Processor,
            generate_first_frame_mask,
        )

        if first_frame is None:
            raise RuntimeError(
                "MatAnyone 2 requires first_frame "
                "for SAM2 mask generation"
            )

        if device is None:
            device = get_device()

        mask = generate_first_frame_mask(
            first_frame, device
        )
        return MatAnyone2Processor(
            first_frame_mask=mask, device=device
        )

    raise ValueError(
        f"Unknown variant '{variant}'. Use: {VARIANTS}"
    )
