"""AI matte generation — protocol, factory, and wrappers.

Supports pluggable matting backends:
- RVM (Robust Video Matting): fully automatic, no first-frame mask
- MatAnyone 2: requires first-frame mask (auto-generated by SAM2)

POV mode:
- MatAnyone 2: SAM2 selects the non-POV person (quality)
- RVM: SAM2 identifies POV body, subtracted per-frame (fast/rough)

All processors implement the MatteProcessor protocol so the pipeline
runner can use them interchangeably.
"""

from typing import Protocol, runtime_checkable

import numpy as np
import torch
from loguru import logger

from vrautomatte.utils.gpu import get_device

# Valid model variant names
VARIANTS = [
    "mobilenetv3", "resnet50",
    "mobilenetv3_onnx", "resnet50_onnx",
    "matanyone2", "sam2matting",
]


@runtime_checkable
class MatteProcessor(Protocol):
    """Protocol for video matting processors."""

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process a single RGB frame → alpha matte.

        Args:
            frame: RGB array (H, W, 3), uint8.

        Returns:
            Alpha matte (H, W), uint8 (0-255).
        """
        ...

    def reset(self) -> None:
        """Reset internal state between videos."""
        ...

    def cleanup(self) -> None:
        """Release GPU memory and model resources."""
        ...


class AlphaSmoother:
    """EMA temporal smoothing wrapper for any MatteProcessor.

    Blends consecutive alpha frames to reduce frame-to-frame jitter.
    alpha_out = weight * current + (1 - weight) * previous

    Args:
        inner: The actual MatteProcessor to wrap.
        weight: Blend weight for the current frame (0..1).
            1.0 = no smoothing (pass-through), lower = smoother.
    """

    def __init__(
        self,
        inner: MatteProcessor,
        weight: float = 0.85,
    ):
        self._inner = inner
        self._weight = weight
        self._prev: np.ndarray | None = None
        self._prev_r: np.ndarray | None = None

    @property
    def supports_pair(self) -> bool:
        """Pair mode available iff the inner processor has it."""
        return getattr(self._inner, "supports_pair", False)

    def _blend(self, matte, prev):
        if prev is None:
            return matte
        blended = (
            self._weight * matte.astype(np.float32)
            + (1.0 - self._weight)
            * prev.astype(np.float32)
        )
        return blended.clip(0, 255).astype(np.uint8)

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process frame and blend with previous matte."""
        matte = self._blend(
            self._inner.process_frame(frame), self._prev
        )
        self._prev = matte.copy()
        return matte

    def process_frame_pair(self, left, right):
        """Pair processing with per-eye smoothing state."""
        lm, rm = self._inner.process_frame_pair(left, right)
        lm = self._blend(lm, self._prev)
        rm = self._blend(rm, self._prev_r)
        self._prev = lm.copy()
        self._prev_r = rm.copy()
        return lm, rm

    def reset(self) -> None:
        """Reset inner processor and smoothing state."""
        self._inner.reset()
        self._prev = None
        self._prev_r = None

    def cleanup(self) -> None:
        """Release inner processor resources."""
        self._inner.cleanup()
        self._prev = None
        self._prev_r = None


class POVExclusionProcessor:
    """Wrapper that subtracts a POV body mask from RVM output.

    SAM2 generates an initial POV body mask from frame 1.
    A scene change detector monitors for drastic changes
    (e.g. laying → standing) and regenerates the mask.

    Pair mode is forwarded to the inner processor so SBS eye
    batching stays available with POV enabled; the right eye
    gets its own exclusion mask, generated lazily from the
    first right frame.

    Args:
        inner: The actual MatteProcessor (e.g. RVMProcessor).
        pov_body_mask: Binary mask (H, W), uint8 (0 or 255).
        device: GPU device for SAM2 reloads on scene change.
    """

    def __init__(
        self,
        inner: MatteProcessor,
        pov_body_mask: np.ndarray,
        device: torch.device | None = None,
    ):
        from vrautomatte.pipeline.scene_detect import (
            SceneChangeDetector,
        )

        self._inner = inner
        self._device = device or get_device()
        self._set_exclusion_mask(pov_body_mask)
        self._exclusion_r: np.ndarray | None = None
        self._scene_detector = SceneChangeDetector()

    @property
    def supports_pair(self) -> bool:
        """Pair mode available iff the inner processor has it."""
        return getattr(self._inner, "supports_pair", False)

    @staticmethod
    def _to_exclusion(mask: np.ndarray) -> np.ndarray:
        """Binary body mask (255=body) -> float keep-factor."""
        return 1.0 - mask.astype(np.float32) / 255.0

    def _set_exclusion_mask(
        self, mask: np.ndarray
    ) -> None:
        """Set or update the (left/primary) exclusion mask."""
        self._exclusion = self._to_exclusion(mask)
        logger.info(
            "POV exclusion mask set — "
            f"covers {(mask > 0).sum()} px"
        )

    def _generate_body_mask(
        self, frame: np.ndarray
    ) -> np.ndarray:
        from vrautomatte.pipeline.sam2_masks import (
            generate_pov_body_mask,
        )
        return generate_pov_body_mask(frame, self._device)

    def _refresh_mask(self, frame: np.ndarray) -> None:
        """Regenerate POV body mask from current frame."""
        logger.info("Scene change — refreshing POV mask")
        self._set_exclusion_mask(
            self._generate_body_mask(frame)
        )
        self._scene_detector.update_reference(frame)

    def _apply_exclusion(
        self, matte: np.ndarray, excl: np.ndarray
    ) -> np.ndarray:
        """Multiply matte by the exclusion keep-factor."""
        if excl.shape != matte.shape:
            from PIL import Image as _Img
            excl_img = _Img.fromarray(
                (excl * 255).astype(np.uint8), mode="L"
            ).resize(
                (matte.shape[1], matte.shape[0]),
                _Img.NEAREST,
            )
            excl = (
                np.array(excl_img).astype(np.float32)
                / 255.0
            )
        result = matte.astype(np.float32) * excl
        return result.clip(0, 255).astype(np.uint8)

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process frame, refresh mask on scene change."""
        if self._scene_detector.check(frame):
            self._refresh_mask(frame)

        matte = self._inner.process_frame(frame)
        return self._apply_exclusion(matte, self._exclusion)

    def process_frame_pair(self, left, right):
        """Batched two-eye processing with per-eye exclusion."""
        if self._exclusion_r is None:
            logger.info(
                "POV pair mode: generating right-eye "
                "exclusion mask..."
            )
            self._exclusion_r = self._to_exclusion(
                self._generate_body_mask(right)
            )
        if self._scene_detector.check(left):
            self._refresh_mask(left)
            self._exclusion_r = self._to_exclusion(
                self._generate_body_mask(right)
            )

        lm, rm = self._inner.process_frame_pair(left, right)
        return (
            self._apply_exclusion(lm, self._exclusion),
            self._apply_exclusion(rm, self._exclusion_r),
        )

    def reset(self) -> None:
        """Reset inner processor and scene detector."""
        self._inner.reset()
        self._scene_detector.reset()

    def cleanup(self) -> None:
        """Release inner processor resources."""
        self._inner.cleanup()


def create_processor(
    variant: str,
    device: torch.device | None = None,
    downsample_ratio: float = 0.25,
    first_frame: np.ndarray | None = None,
    pov_mode: bool = False,
    *,
    use_fp16: bool = True,
    max_internal_size: int = 480,
    max_mem_frames: int = 3,
    use_long_term: bool = True,
    compile_model: bool = False,
    roi_matting: bool = False,
    max_subjects: int = 1,
    matte_stride: int = 1,
) -> MatteProcessor:
    """Create a matting processor for the given variant.

    For matanyone2: generates SAM2 mask from first_frame,
    unloads SAM2, then loads MatAnyone 2 (D003).

    Args:
        variant: One of 'mobilenetv3', 'resnet50', 'matanyone2'.
        device: Target device. Auto-detected if None.
        downsample_ratio: RVM downscale (ignored for MA2).
        first_frame: First video frame (required for matanyone2).
        pov_mode: If True, select non-POV person mask.
        use_fp16: MatAnyone2 only — FP16 weights + activations.
        max_internal_size: MatAnyone2 only — memory encoding
            resolution (px short side). 480 recommended for 4K+.
        max_mem_frames: MatAnyone2 only — working-memory slots.
        use_long_term: MatAnyone2 only — XMem long-term memory.
        compile_model: MatAnyone2 only — torch.compile opt-in.

    Returns:
        A MatteProcessor instance.
    """
    # ── ONNX Runtime variants (DirectML / CUDA EP / CPU) ──
    if variant in ("mobilenetv3_onnx", "resnet50_onnx"):
        from vrautomatte.pipeline.rvm_onnx import (
            RVMOnnxProcessor,
        )
        base_variant = variant.replace("_onnx", "")
        processor = RVMOnnxProcessor(
            variant=base_variant,
            downsample_ratio=downsample_ratio,
        )

        if pov_mode and first_frame is not None:
            from vrautomatte.pipeline.sam2_masks import (
                generate_pov_body_mask,
            )
            if device is None:
                device = get_device()
            logger.info(
                "RVM ONNX + POV: generating exclusion mask..."
            )
            body_mask = generate_pov_body_mask(
                first_frame, device
            )
            return POVExclusionProcessor(
                processor, body_mask, device=device
            )
        elif pov_mode:
            logger.warning(
                "POV mode requires first_frame for RVM — "
                "falling back to standard matting"
            )

        return processor

    # ── PyTorch TorchScript variants ───────────────────────
    if variant in ("mobilenetv3", "resnet50"):
        from vrautomatte.pipeline.rvm import RVMProcessor
        processor = RVMProcessor(
            variant=variant,
            downsample_ratio=downsample_ratio,
            device=device,
            use_fp16=use_fp16,
        )

        if roi_matting:
            # ROI wraps the raw model; POV exclusion (below)
            # stays outside so its full-frame mask geometry is
            # applied to the pasted-back full-size matte.
            from vrautomatte.pipeline.roi import ROICropper
            logger.info("ROI cropping enabled")
            processor = ROICropper(processor)

        if pov_mode and first_frame is not None:
            from vrautomatte.pipeline.sam2_masks import (
                generate_pov_body_mask,
            )
            if device is None:
                device = get_device()
            logger.info(
                "RVM + POV: generating exclusion mask..."
            )
            body_mask = generate_pov_body_mask(
                first_frame, device
            )
            return POVExclusionProcessor(
                processor, body_mask, device=device
            )
        elif pov_mode:
            logger.warning(
                "POV mode requires first_frame for RVM — "
                "falling back to standard matting"
            )

        return processor

    if variant == "sam2matting":
        from vrautomatte.pipeline.sam2matting import (
            SAM2MattingProcessor,
            prepare_environment,
        )

        if first_frame is None:
            raise RuntimeError(
                "SAM2Matting requires first_frame "
                "for mask generation"
            )

        from vrautomatte.pipeline.sam2_masks import (
            generate_first_frame_mask,
        )

        if device is None:
            device = get_device()

        # First-frame masks need the STOCK sam2 install — the
        # mask generator itself sidelines the fork via
        # stock_sam2(); prepare_environment() below then
        # reloads the fork for the matting model.
        if max_subjects > 1:
            from vrautomatte.pipeline.sam2_masks import (
                generate_person_masks,
            )
            masks = generate_person_masks(
                first_frame, device,
                max_people=max_subjects,
                pov_mode=pov_mode,
            )
            logger.info(
                f"SAM2Matting: tracking {len(masks)} "
                f"subject(s) (requested {max_subjects})"
            )
        else:
            masks = generate_first_frame_mask(
                first_frame, device, pov_mode=pov_mode
            )
        prepare_environment()
        return SAM2MattingProcessor(
            first_frame_mask=masks,
            device=device,
            compile_model=compile_model,
            matte_stride=matte_stride,
        )

    if variant == "matanyone2":
        from vrautomatte.pipeline.matanyone2 import (
            MatAnyone2Processor,
        )
        from vrautomatte.pipeline.sam2_masks import (
            generate_first_frame_mask,
        )

        if first_frame is None:
            raise RuntimeError(
                "MatAnyone 2 requires first_frame "
                "for SAM2 mask generation"
            )

        if device is None:
            device = get_device()

        mask = generate_first_frame_mask(
            first_frame, device, pov_mode=pov_mode
        )
        processor = MatAnyone2Processor(
            first_frame_mask=mask,
            device=device,
            pov_mode=pov_mode,
            use_fp16=use_fp16,
            max_internal_size=max_internal_size,
            max_mem_frames=max_mem_frames,
            use_long_term=use_long_term,
            compile_model=compile_model,
        )
        if roi_matting:
            from vrautomatte.pipeline.roi import ROICropper
            logger.info(
                "ROI cropping enabled (MatAnyone 2 reseeds "
                "on window moves)"
            )
            processor = ROICropper(processor)
        return processor

    raise ValueError(
        f"Unknown variant '{variant}'. Use: {VARIANTS}"
    )
