"""AI matte generation — protocol, factory, and wrappers.

Supports pluggable matting backends:
- RVM (Robust Video Matting): fully automatic, no first-frame mask
- MatAnyone 2: requires first-frame mask (auto-generated by SAM2)

POV mode:
- MatAnyone 2: SAM2 selects the non-POV person (quality)
- RVM: SAM2 identifies POV body, subtracted per-frame (fast/rough)

All processors implement the MatteProcessor protocol so the pipeline
runner can use them interchangeably.
"""

from typing import Protocol, runtime_checkable

import numpy as np
import torch
from loguru import logger

from vrautomatte.utils.gpu import get_device

# Valid model variant names
VARIANTS = ["mobilenetv3", "resnet50", "matanyone2"]


@runtime_checkable
class MatteProcessor(Protocol):
    """Protocol for video matting processors."""

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process a single RGB frame → alpha matte.

        Args:
            frame: RGB array (H, W, 3), uint8.

        Returns:
            Alpha matte (H, W), uint8 (0-255).
        """
        ...

    def reset(self) -> None:
        """Reset internal state between videos."""
        ...

    def cleanup(self) -> None:
        """Release GPU memory and model resources."""
        ...


class POVExclusionProcessor:
    """Wrapper that subtracts a static POV body mask.

    Used with RVM for fast-but-rough POV mode. SAM2 generates
    a POV body mask from frame 1. Each frame's alpha output
    is zeroed wherever the POV mask is active.

    The mask is static (frame 1 only) so won't track large
    POV body movements, but works well for typical POV
    content where the camera holder stays relatively still.

    Args:
        inner: The actual MatteProcessor (e.g. RVMProcessor).
        pov_body_mask: Binary mask (H, W), uint8 (0 or 255).
    """

    def __init__(
        self,
        inner: MatteProcessor,
        pov_body_mask: np.ndarray,
    ):
        self._inner = inner
        # Normalize to float 0-1 for multiplication
        self._exclusion = (
            1.0 - pov_body_mask.astype(np.float32) / 255.0
        )
        logger.info(
            "POV exclusion wrapper active — "
            f"mask covers {(pov_body_mask > 0).sum()} px"
        )

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process frame then subtract POV body region."""
        matte = self._inner.process_frame(frame)

        # Resize exclusion mask if frame size differs
        excl = self._exclusion
        if excl.shape != matte.shape:
            from PIL import Image as _Img
            excl_img = _Img.fromarray(
                (excl * 255).astype(np.uint8), mode="L"
            ).resize(
                (matte.shape[1], matte.shape[0]),
                _Img.NEAREST,
            )
            excl = 1.0 - np.array(excl_img).astype(
                np.float32
            ) / 255.0

        result = (matte.astype(np.float32) * excl)
        return result.clip(0, 255).astype(np.uint8)

    def reset(self) -> None:
        """Reset inner processor state."""
        self._inner.reset()

    def cleanup(self) -> None:
        """Release inner processor resources."""
        self._inner.cleanup()


def create_processor(
    variant: str,
    device: torch.device | None = None,
    downsample_ratio: float = 0.25,
    first_frame: np.ndarray | None = None,
    pov_mode: bool = False,
) -> MatteProcessor:
    """Create a matting processor for the given variant.

    For matanyone2: generates SAM2 mask from first_frame,
    unloads SAM2, then loads MatAnyone 2 (D003).

    Args:
        variant: One of 'mobilenetv3', 'resnet50', 'matanyone2'.
        device: Target device. Auto-detected if None.
        downsample_ratio: RVM downscale (ignored for MA2).
        first_frame: First video frame (required for matanyone2).
        pov_mode: If True, select non-POV person mask.

    Returns:
        A MatteProcessor instance.
    """
    if variant in ("mobilenetv3", "resnet50"):
        from vrautomatte.pipeline.rvm import RVMProcessor
        processor = RVMProcessor(
            variant=variant,
            downsample_ratio=downsample_ratio,
            device=device,
        )

        if pov_mode and first_frame is not None:
            from vrautomatte.pipeline.sam2_masks import (
                generate_pov_body_mask,
            )
            if device is None:
                device = get_device()
            logger.info(
                "RVM + POV: generating exclusion mask..."
            )
            body_mask = generate_pov_body_mask(
                first_frame, device
            )
            return POVExclusionProcessor(
                processor, body_mask
            )
        elif pov_mode:
            logger.warning(
                "POV mode requires first_frame for RVM — "
                "falling back to standard matting"
            )

        return processor

    if variant == "matanyone2":
        from vrautomatte.pipeline.matanyone2 import (
            MatAnyone2Processor,
        )
        from vrautomatte.pipeline.sam2_masks import (
            generate_first_frame_mask,
        )

        if first_frame is None:
            raise RuntimeError(
                "MatAnyone 2 requires first_frame "
                "for SAM2 mask generation"
            )

        if device is None:
            device = get_device()

        mask = generate_first_frame_mask(
            first_frame, device, pov_mode=pov_mode
        )
        return MatAnyone2Processor(
            first_frame_mask=mask, device=device
        )

    raise ValueError(
        f"Unknown variant '{variant}'. Use: {VARIANTS}"
    )
